### ISSUE TITLE
Meta: Requirements use by pkg/angular_analyzer

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/angular_ast#17]
- [ ] Support parsing expressions without throwing when a failure occurs
- [ ] Include offset data in `parseExpression`
- [ ] Add `visitExpression` to `TemplateAstVisitor`
- [ ] Add support for `accept` to `BananaAst` and `StarAst` for tooling teams
- [ ] Check trailing expressions ([see implementation][trailing])
- [x] `TemplateAstVisitor#visit` should delegate to `TemplateAst#accept`.

[trailing]: https://github.com/dart-lang/angular_analyzer_plugin/pull/94/files#diff-dd70e04facf5d905f5ff348ad54053f3R987
